#!/usr/bin/env bash
# =============================================================================
# Deploy Agentic Microservices Showcase infrastructure to Azure
# Prerequisites:
#   - Azure CLI >= 2.61.0  (az --version)
#   - Bicep CLI >= 0.28     (az bicep version)
#   - Contributor role on the target resource group
# =============================================================================

set -euo pipefail

# ---------------------------------------------------------------------------
# Configuration — edit these or export as environment variables
# ---------------------------------------------------------------------------
RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-rg-agentic-showcase-dev}"
LOCATION="${AZURE_LOCATION:-eastus2}"
SUBSCRIPTION="${AZURE_SUBSCRIPTION_ID:-}"

# Optional: set a specific subscription
if [[ -n "$SUBSCRIPTION" ]]; then
  az account set --subscription "$SUBSCRIPTION"
fi

echo "Resource group : $RESOURCE_GROUP"
echo "Location       : $LOCATION"
echo "Subscription   : $(az account show --query id -o tsv)"
echo ""

# ---------------------------------------------------------------------------
# 1. Create resource group (idempotent)
# ---------------------------------------------------------------------------
az group create \
  --name "$RESOURCE_GROUP" \
  --location "$LOCATION" \
  --output none

echo "✓ Resource group ready."

# ---------------------------------------------------------------------------
# 2. Deploy Bicep
# ---------------------------------------------------------------------------
DEPLOYMENT_NAME="agents-$(date +%Y%m%d-%H%M%S)"

OUTPUTS=$(az deployment group create \
  --resource-group "$RESOURCE_GROUP" \
  --name "$DEPLOYMENT_NAME" \
  --template-file "$(dirname "$0")/main.bicep" \
  --parameters "$(dirname "$0")/parameters/dev.bicepparam" \
  --output json \
  --query 'properties.outputs')

echo "✓ Bicep deployment complete."
echo ""

# ---------------------------------------------------------------------------
# 3. Extract outputs and write .env
# ---------------------------------------------------------------------------
ENV_FILE="$(dirname "$0")/../.env"

OPENAI_ENDPOINT=$(echo "$OUTPUTS" | jq -r '.openAiEndpoint.value')
SERVICEBUS_NS=$(echo "$OUTPUTS" | jq -r '.serviceBusNamespace.value')
APPINSIGHTS_CS=$(echo "$OUTPUTS" | jq -r '.appInsightsConnectionString.value')
KEYVAULT_URI=$(echo "$OUTPUTS" | jq -r '.keyVaultUri.value')

cat > "$ENV_FILE" <<EOF
# Auto-generated by infra/deploy.sh — do not commit
AZURE_OPENAI_ENDPOINT=$OPENAI_ENDPOINT
AZURE_OPENAI_DEPLOYMENT_NAME=gpt-4o
AZURE_OPENAI_EMBEDDING_DEPLOYMENT=text-embedding-3-small
AZURE_OPENAI_API_VERSION=2024-12-01-preview
AZURE_SERVICEBUS_NAMESPACE=$SERVICEBUS_NS
APPINSIGHTS_CONNECTION_STRING=$APPINSIGHTS_CS
AZURE_KEY_VAULT_URI=$KEYVAULT_URI
AZURE_RESOURCE_GROUP=$RESOURCE_GROUP
EOF

echo "✓ .env written to $ENV_FILE"
echo ""
echo "Next step: source .env && jupyter lab"
